=== CLHB8/digital-learning-imbit/brillianideas/ux/xsd/Learning.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="learningType" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="youtube" />
      <xs:enumeration value="video" />
      <xs:enumeration value="website" />
      <xs:enumeration value="podcast" />
      <xs:enumeration value="seriousGame" />
      <xs:enumeration value="application" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Learning">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Title"/>
        <xs:element type="xs:string" name="Description"/>
        <xs:element name="Source">
          <xs:complexType>
            <xs:sequence>
			  <xs:choose>
				  <xs:element name="URI">
					<xs:complexType>
					  <xs:attribute type="xs:boolean" name="embedded" />
					  <xs:attribute type="xs:anyURI" name="src" />
					</xs:complexType>  
				  </xs:element>
				  <xs:element name="Video">
				    <xs:complexType>
					  <xs:attribute type="xs:boolean" name="embedded" />
					  <xs:attribute type="xs:string" name="id" />
					</xs:complexType>
				  </xs:element>
				  <xs:element name="App">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Android">
								<xs:complexType>
									<xs:attribute type="xs:string" name="id" />
								</xs:complexType>
							</xs:element>
							<xs:element name="iOS">
								<xs:complexType>
									<xs:attribute type="xs:string" name="id" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				  </xs:element>
			  </xs:choose>
              <xs:element type="xs:string" name="Author"/>
              <xs:element type="xs:string" name="Copyright"/>
              <xs:element type="xs:date" name="Stand" />
              <xs:element type="xs:duration" name="Duration" minOccurs="0" maxOccurs="1" />
              <xs:element name="Thumbnail">
                <xs:complexType>
                   <xs:attribute type="xs:anyURI" name="src"/>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:boolean" name="certificateCosts" minOccurs="0" maxOccurs="1" nillable="true" />
            </xs:sequence>
            <xs:attribute type="learningType" name="type"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="MetaInformation">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Class"/>
              <xs:element type="xs:string" name="Professor" minOccurs="0" maxOccurs="1"/>
              <xs:element type="guid" name="Recommended" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="guid" name="guid"/>
      <xs:attribute type="xs:boolean" name="cost"/>
      <xs:attribute type="xs:boolean" name="offerLimited"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CLHB8/digital-learning-imbit/brillianideas/ux/examples/Webseite_UML_Tutorial.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="d21a1287-1be0-41ba-9b8c-0cdc01764fd4" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>UML Tutorial (Englisch)</Title>
  <Description>
	Webseite zum lernen des "unified modeling language" - bereitgestellt von "tutorialspoint". Hier werden Sie lernen wof√ºr UML gedacht ist und wie man diese Sprache einsetzt.
	Dieses Tutorial ist auf englisch.
  </Description>
  <Source type="website">
    <URI embedded="false" src="http://www.tutorialspoint.com/uml/"/>
    <Author>Mohtashim M.</Author>
    <Copyright>Tutorialspoint (2017)</Copyright>
    <Stand>2015</Stand>
    <!-- Optional ab hier -->
    <Thumbnail src="https://www.tutorialspoint.com/green/images/logo.png"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>BWL</Class>
    <!-- Optional ab hier -->
    <Professor>Prof. Bendl</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/brillianideas/ux/examples/Internetworking_mit_TCP-IP_website.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="b8384699-84d7-4251-9161-0b911487f5ac" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Internetworking mit TCP/IP</Title>
  <Description>
	Dieser Kurs bringt Ihnen die technologischen Grundlagen des Internets näher. Er behandelt die physikalischen Grundlagen der Datenübertragung basierend auf funktionalen Prinzipien und Technologien von Local Area Networks (LANS) und Wide Area Networks (WANs). Außerdem lernen die Teilnehmer das TCP/IP reference model - das Herz des Internets - kennen und steigen somit in die komplexe Welt der Internettechnologoien ein.
	
  </Description>
  <Source type="website">
    <URI embedded="false" src="https://open.hpi.de/courses/internetworking2014"/>
    <Author>Prof. Dr. Christoph Meinel</Author>
    <Copyright>Hasso-Plattner-Institut</Copyright>
    <Stand>2014</Stand>
	
    <!-- Optional ab hier -->
    <Thumbnail src="http://educationcareerarticles.com/wp-content/uploads/2013/04/Internetwork-Engineering.jpg"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>Kommunikationssysteme</Class>
    <!-- Optional ab hier -->
    <Professor>Sebastian Welter</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/OpenHPI_website.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="750576dd-7e5b-437f-87e8-87bbe2359145" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>OpenHPI</Title>
  <Description>
MOOCs – Massive Open Online Courses – bieten eine der innovativsten Lernformen: Frei über das Internet können Lernende auf didaktisch aufbereitete multimediale Kursmaterialien zugreifen und vermittels Social Media im engen Austausch mit den anderen Kursteilnehmern lernen. Wer sich mit solchen MOOCs im Bereich der sich rasant entwickelnden Informationstechnologien aus- und weiterbilden will, ist bei open HPI, der MOOC-Plattform des Hasso-Plattner-Instituts genau richtig!
	
  </Description>
  <Source type="website">
    <URI embedded="false" src="https://open.hpi.de/"/>
    <Author>Prof. Dr. Christoph Meinel</Author>
    <Copyright>Hasso-Plattner-Institut</Copyright>
    <Stand>2017</Stand>
	
    <!-- Optional ab hier -->
    <Thumbnail src="https://pbs.twimg.com/profile_images/378800000827898552/669f90369b095789252ae6f0649bc39a_400x400.png"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>All</Class>
    <!-- Optional ab hier -->
    <Professor>-</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/brillianideas/ux/examples/exmple_youtube_embedded.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="3ece1853-8c86-45db-a57e-f665ee33d8a8" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Michael Porter's 5 Forces model explained</Title>
  <Description>
	This webseminar explains the five forces model of Michael Porter. Also explained in this video how this model can be used in practice.
  </Description>
  <Source type="youtube">
    <Video embedded="true" id="33XmkfbzwO8"/>
    <Author>Pepijn Schoemaker</Author>
    <Copyright>Pepijn Schoemaker</Copyright>
    <Stand>2016-03-21</Stand>
    <!-- Optional ab hier -->
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>BWL</Class>
    <!-- Optional ab hier -->
    <Professor>Prof. Bendl</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/exmple_website.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="3ece1853-8c86-45db-a57e-f665ee33d8a7" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>St. Galler Management Model</Title>
  <Description>
	Management wird anspruchsvoller und kontroverser. In einer unübersichtlichen und vernetzten Welt beruht wirksames Management auf vielfältigen Voraussetzungen. Diese fundiert zu verstehen, wird noch wichtiger. Nur auf dieser Grundlage kann die eigene Management-Praxis so gestaltet werden, dass sich die organisationale Wertschöpfung im Zusammenspiel mit der steigenden Umweltdynamik erfolgreich weiterentwickelt.
	Für Manager-Communities ist es unerlässlich, sowohl die verantwortete Wertschöpfung als auch die eigene Management-Praxis sorgfältig zu reflektieren. Hierzu sind eine differenzierte Sprache und ein integrativer Ordnungsrahmen erforderlich, die es erlauben, die komplexen Herausforderungen, mit denen sich die heutige Management-Praxis konfrontiert sieht, greifbar zu machen und diskutieren zu können. Genau dazu dient das St. Galler Management-Modell (SGMM) seit der 1. Generation von Hans Ulrich und Walter Krieg (1972).
	Dieses traditionsreiche Management-Modell der Universität St. Gallen (HSG) ist 2015 grundlegend weiterentwickelt worden und neu in der 4. Generation im praktischen Einsatz.
	Es stellt ein Arbeitsinstrument und eine Reflexionshilfe für eine vertiefte Auseinander­setzung mit Management dar und unterstützt die Lehre in der Ausbildung von Studierenden und Praktikern, sowie die unternehmerische Praxis und die wissen­schaftliche Forschung bei Fragen der Management-Innovation.
  </Description>
  <Source type="website">
    <URI embedded="false" src="https://www.sgmm.ch/"/>
    <Author>Johannes Rüegg-Stürm &amp; Simon Grand</Author>
    <Copyright>Institut für Systemisches Management und Public Governance (IMP-HSG)</Copyright>
    <Stand>2015</Stand>
    <!-- Optional ab hier -->
    <Thumbnail src="https://www.sgmm.ch/wp-content/themes/theme-sgmm/build/img/ikone-sgmm.png"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>BWL</Class>
    <!-- Optional ab hier -->
    <Professor>Prof. Bendl</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/Amazing_SQL_website.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="c5aa8c91-165b-42f7-afb2-70eaffb8329a " cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Amazing SQL</Title>
  <Description>
	Amazing SQL ist eine kostenlose Software, mit der man SQL-Abfragen in verschiedenen Schwierigkeitsstufen Ã¼ben kann.
  </Description>
  <Source type="website">
    <URI embedded="false" src="http://amazing-sql.com/"/>
    <Author>Andreas Palosi und Jan Freidinger</Author>
    <Copyright>-</Copyright>
    <Stand>2017</Stand>
	
    <!-- Optional ab hier -->
    <Thumbnail src="http://amazing-sql.com/images/logo_small.png"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>Datenbanken</Class>
    <!-- Optional ab hier -->
    <Professor>Sebastian Welter</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/exmple_app.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="3ece1853-8c86-45db-a57e-f665ee33d8a9" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Englisch lernen mit Babbel</Title>
  <Description>
	Du hast beim Vokabellernen endlich alle Wörter von „Aal“ bis „azurblau“ durch? Bleiben nur noch … 25 weitere Buchstaben … Wie wär’s stattdessen mit nützlichen Wörtern und Sätzen, mit denen du dich auf deiner nächsten Reise auch wirklich auf Englisch unterhalten kannst? Mit den Sprachkursen von Babbel übst du keine endlosen Vokabellisten oder unwichtigen Sätze. Wir möchten, dass du dich traust, Englisch zu sprechen – und zwar so, wie du es schon immer wolltest!
	</Description>
  <Source type="application">
    <App>
		<Android id="com.babbel.mobile.android.de" />
		<iOS id="477147527" />
	</App>
    <Author>Lesson Nine GmbH</Author>
    <Copyright>Lesson Nine GmbH</Copyright>
    <Stand>2017</Stand>
    <!-- Optional ab hier -->
    <Thumbnail src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAAAoCAYAAAA2cfJIAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw%2FeHBhY2tldCBiZWdpbj0i77u%2FIiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8%2BIDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpBQTU5ODEyRjUzQUExMUUzOTQ2MUI4NTUyMTk0MkMzNSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpBQTU5ODEzMDUzQUExMUUzOTQ2MUI4NTUyMTk0MkMzNSI%2BIDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjZCNjBFODkwNTNBQTExRTM5NDYxQjg1NTIxOTQyQzM1IiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOkFBNTk4MTJFNTNBQTExRTM5NDYxQjg1NTIxOTQyQzM1Ii8%2BIDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY%2BIDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8%2BzOeBKgAADspJREFUeNrsXAmQVcUVvZ%2F582f5szkMDKvs%2BxLAAsQtaFRcUEQ0FRILrZSmEqqyEDGoqaRMjFVJkGjQaGI2IzG4EUwiicoaNCAMogFklS2RZYBhG5iVmZ973u03r1%2B%2F9%2F5%2Ff2QmBUyXXaN%2F3u93%2B%2Fbpc8%2B93WMkMaeEUrRi7jdzv537EO6F3LO4x7hHuWdwj6je1s6t1hBN8kv87nru93K%2FnPtF6jNqW%2BzzptUGASCf%2B%2F3cp3Pv0Oan87bV%2BAEgm%2FtD3Gdxb9fmo%2FO6Vfst8BTuX2tb%2FAuinTIXuRv3%2B7gXtfnmgmjHzRBwDfcRrfPuhPWPb4u06cxWaseihtvHqzSvBde9kai%2BmpPHTA4yARq0oZ6o8YyyirPMaHYLGMLTbaiV90RUFpv2e87GGP%2FXuVREjXx%2FaIsvPhb%2BMtaXPcYHAwATqTlGtH8t0c63iA5%2BwN%2BLBT%2FfrAy4hqhkENG4B4nySonKniba8bf0FhBjdBjC8%2BExckuI1s4l%2BvjvrQ8Cy46hYkc2Z%2BtlPxe%2Fpbaj3ARAtxY19Azv%2FCu%2FRzTmW%2BGe7z2BaOxMok3ziFb%2BkJmjkkEQOwtAbCCKFRDd%2BEuiTiPls4v6MNDWsyw6KCANM0YWk%2BVNzxF1HCafFfUUsFYdYjszW2fxm%2BzguXQcLp8VXsxL%2B2%2B243AqO8p1EXhRs%2Bj%2FDFNPfZUYkmr3x%2FKJ%2BkxIb%2FzMHKKRXyG69XlemOzU7wm1YzjEFPVih2mEF8sjyoELGkOOUSegAQM02cpjZBfJXFtt99d77YCfs0LZcUgHQHtVA0jj5bXy4h5XM93kOHE7CABAajTXABDTV%2F1ppwNQfq3XtUTDpgmLnI1QFIu7d0ftSelhs99EQkAT0Z6vrZQxIq2YQVtzyROtZLc6tqMulB1H9BBQklbuj4UYwRnj%2BEfFgB2LiBbdKzvD78W20%2FGsngm8OZ1p80MtXrGAad%2BP6NIH3KhGG3Ab0Qe%2FOjsZSLaR6VpOO5XG4mGM4k85xlnKpnKKnX%2BH%2F2BDajtqTREYvuSLnR7vxAJqprOg%2FW4WIfLJaqHtoBCgAwChA7Hq0CYGQJZKRHgS%2B9dILJ3KQiavk%2FN8vIOwCJhCR3xzWq5xCGY5rTK9xYt38B8jI5NateV20PNn8Q9sSW4HqPSkKQJDAoDjcLyjKE6dEWqOModkJKeqjCy3w8AYAEyGJu7ABke2MD63uAGA%2BB8U1%2FA5xjI1AhYU7zQXNtdYvJrj0k3ljMxDtzkZiJC5gHqjxgZAqMkIKV4RWhBazXlYdsT86yN%2BdjTWpXono4Qqo4YGSEN5sorOzHWcv%2BYJXrDtSVKPNGgXTsDYYAyXyayua0%2B4HQw2go4AuCDqoIDBTli06gqi47uZYTYIQPXvmQDAuFDRGCNeqgqlBwWIR7cL41hA0KpXOYbjaxlAHUeoMTrKsxjjMI9xbIf%2FGPqcz1SJjaVsR1FvNYayAzYc2SbfNX1szqXqSJhC2gmMHI4BrN1V7xiO%2Fz6%2Bi2jZg%2BJ80Pi%2B1YJSS8Sp58AGutDK9aFMSzRFxAGyooxgtq3HZ1mVDHY%2Fv%2Fef2s6ISP4L9A%2B9i%2FXBZIbwAAeUOlgRllb%2BgH%2Bucn5v2gIhe8%2F1%2FPu4QZS8m3Zybr%2FqJ7yIO9XvE%2F5j9OLv953otQFAhEZa%2FVN2OwMyGneDoLFe5j%2F485LxdBrlXWT4ac8yovdmS3jU7fQFAIUBQLUNgKg%2FAFSFCRTdvr%2FSiEpowLE7%2F%2BHQrJVPR9zUizy0cr8zGQ9VnZB4ZTksodDN7%2Bp7BdHnfux2JCa15VWnDgC6L%2BL057Z5oj0Ci2QMwu483hT%2B7quTiA6s97clO%2BD4A6nh0C8RdbuM6PUvMptsVEwSSWMMJtfhnMF0v5xo4VRhFdsnWHykt9fNkfcENTAuRDAKaG98mX3%2FpgJBRMZ3AeBwqDIwafcBslUdwIj17OSCbkQ3PEPU%2BRJF1YmQ1cl2smhLZkp1zA%2BppZ8hmvaOoxvs1Ao72YzPS%2B7XdiBsY2AO%2BYJ38cFAiIFQxnoMxOKMm0W04E6h4aw0Sx6oG9zEGcj8GxVo494QlaohX0fB5qWJwl5Ck%2FzZs8JgnkyrxssEmAcKWC9eJyzsZ0c4BjgKL9oAAKQLfPP8sTOEjpvTCrrL93e84Q8ATKbL6NTjbPwj0eZXNBGUkJ1d%2FqGj3PeVEW19Tap5oMtsXuCrHmFavs4ZByAGoPF7VzrK7cA6%2Fv5CdupOCVtgjWF3uakWGmEwA6jsFzxOsXcMlK63vc5A3SUK%2FOKrZFfrTAZ6H3Q70Ye%2FE8CPe8C7%2BFsWEG3iOZ8uF%2FbF70d91SmFQxuM4lDx9jfFp6Yd1aEZoOmKF0bwh3Ne50%2BXomASTTGzpHljXMKTL%2Bbds%2FjbHFL2yQ4GDaPejZ0AABzZLLvfdlI564t3HiXqeY2TMloVsgIRjqbTls6SGAuHw9yP5hPtXkI06QW3eOzPNPz%2Bs%2FJ9s6ax9DuiU6wx%2BL8%2FeknGuPUP7p0MKl%2F%2FHDNCX6LRX3fbUTaXx2FQJCIyF4TaPSskVIyZ4TzX82phMUssG3bUVIYp6VSQ9hR2f9zzCHYCJntir4hAxF2r13rTMRiKz%2B1nQF%2F7eVe%2B%2BxgvQFScGCtoHgDgiD5MvRN%2FKxO2hSBCBxYeTHCmTonJBnmmfR%2FJBizxSo7AbFT1iMx8d9iAzXCkRalxSXG3%2F4WZ52UjFPQU9Y8F1akXNQ3XGHnCQtsWCjPprbCXLF7v692seGIPC8XZonNgA2ojmAuYb8trEpJ14YcOsJl21J9Sp4LJq4A6AxT5loEhTv6zUnZZfme1kROyg25%2Bzh1%2Fy55i2npRSr0RVStACmYXRswiENr7HMvK17vzbPv4FzoAO0WvNUCIDWD63PC8ONkCXZ2wFOi9yxjRFXldRAMgxOg7D8fQsAe1hVg8dToKgIEVht%2Bj1fsVQLAwOrX7Vt8iMsbeFZKpuMbIlxDhCok81zsWeE89wSYAg178wrhY5Mx4CDt822EdAMgAMn1zdywOVOWpA85OBzBMMYhyLuJoprbIWHh8H7vQQ5nctrIy373Mv3KIXYl4Onm%2Be4J9bhAAWOqZd8Y4pt3hd4vAStUs53D8zxrgdlBgFTAimYrpE%2BtcoyBkJdFnDHwfcyrsYSj9QgFxmAYdA7FXMtCntpKyotloaoDilBRsoxKORwk0VugtpIDm%2FQpBdhVQpyorpKhY7PcdOGj3YsbpJrdT8rsqlmBg3fJ7BsRNwWcVYCEddPZON7UIKLM%2BYNfYRSGzduH3ue%2FOSzgFnaZnT6pQFW9eSER4XfukACDeOaQd7qdUHSAkAPxq%2Bq4dkAh2oA04CwAhaFcb0tIgnlimKmZXPOxdfDAQUk5oguMcT4dy3n7pTOOdVd7Fq1W2mCVcLJKZAZ38Lzu%2Bwl2ithcV8ddTiGJ7L%2FYZwxLHRoPesMJoTvLDH7Bx%2BQZ%2BV7bPmUalvx1GoggrdACkUQZW8UenbeyIU%2BUi9oJAYwEmEh6pcChSpmKjJlDJk49xbB90p%2Fts4t0fEa35mQhRjIldMnSqkR4dlQUxD3FwhmGKWswJKWq%2Fie7Pdy8VIelbfUt4WRG6pa8BVIQ91DaqK9yfQyRvV7eSTODDPoRFvAILjw0FNvbYURGmVoNzgFN6FhA%2BP0NcR0EGCtmmo%2FfmiOBLdvpkVqvgnNMHlWrV7gMAFPhZOpLo2se9sXbvctl9%2BsQBlo0vyFgQoWAOLHRuR%2F8KWY7hNKSWddXq%2Fadl8SEqUfjRC0bVvMhb%2F8zzzPDuPFQ8zTG6jpXCjx6GcJ4B31m1i1XuMXqz2B55nyysLYitqmujhIuBk4nGcu5f2N3JhEw7cBspdTtuAyCqQBCeAWA4Xv4WG7LhBUEyyqNBJ2ZB9WoA4vKHFANEHHoB%2FSED6DqOnW%2BUJsAycJ6VZ2s7FrdfUFBZxylr3QlJ8XAg0%2F1KfwCYDICQMOAWsQV2ogiEDMSsFiJFA%2FghPk1wAZTWGBH5HRR%2B%2F0leAONMAZsFQEVqd8l0RwtAZ02YK9kVyuwIq3gOh0PIfrqNU%2BKZx%2F7rNAXyDs0tA1faAMhLSwPYyET6tWe5OC3MJUhTCOV3kUuM6WiPFQ%2FJboXDcPKIHWbZE5FK2eCpUgUDlZrvs2m6XTsvG2Gh0JM11EOQttp1iGyjcj5wivRkDanyB78W%2B2EzNg7Y88rvu4%2FCx3xDekPAkS5qEdg02HSmHVUVYRmgwQ4BBb5l4DBMAGeEvQGbmfPpqomLmBo%2FelkEKGLhvx7zXg9D4QXVNb%2FFt8TXPgFSsqtrZsO5wvKH5eQzonJvjJHO3UTEelQaV3yXFy3qxHewHXTLuqcCwm3M3x6wiBUWsr2pNTZI6tZEExmPTMjFTeC702aBdJp1nFwrtJrObRmcgSPMLJ4hJVY7i8AYYIADZbzgvVVqqIkmLDDuABz7WO4HoKGghdQJ6SdEH1LLoNM76Bq8G2cQS2cqYZalDq0izrX1zqMFdEFpKGzcOI9oCYenjxcpcacVc2ybdyHd3SzANQ%2Bx7JNP2IPyNMbap461oXlQIrfTZPio7El1VpI0DcThzArLhMScEgTKV3BMQS3ZMInSEXJsbE0wQKlC0WOBTn7Ck94hognP%2B%2B0GOACgwCFNfjdhGYhLCLKKbbJQKLcitiJcQSyizIrFQWWzkMGTUySUDDqF%2BMLC4gIGTtpwF8AuZvmBBGEMp4SgYYsNVdEL2QZYC3oBGinIflcaXSUAKe4voAUQEONte3DABCbR7bH%2FzgLX5%2FFz19siPlNfSef8mObbALiDf%2F6GWvovgmynhaVOIBiL1S4jHLvootC%2BBmbvRLusrY8FcACUfkC0bu5kpr53CMDoF2U8Y8TSu2NoXQfDtbYz4e2x0sOAOQbTP%2F4EcJMtArHzs6g1Wkv8xYwlQpPoi6Bqm17dbG7DTjubfwCCkGBdjs1Kb%2F7pVRSXI49omgL3riT%2Fm5e2dv43pH%2FPghd1AHShtv8XwIXS5nJf6SIx7qVtfrkg2jPcZ5Pxt2%2FRtKqAbe1cbDjHf4L70yR%2FDEJ%2BAGho0wHnZEtoPxvVT6wl6vycg9Iy7n%2ByFb9f%2B58AAwDsqmwhaajdsgAAAABJRU5ErkJggg%3D%3D"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>Spanisch</Class>
    <!-- Optional ab hier -->
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/Kulturelle_Dimensionen_Globe_website.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="b82da83a-9b73-49c1-933b-2350fee0edd5" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Kulturelle Dimensionen des GLOBE-Projekts</Title>
  <Description>
	Anhand einer interaktiven Lernkarte erfährt man die Ausprägungen der einzelnen Länder in diversen kulturellen Dimensionen, 
	nach denen die Untersuchungen des GLOBE-Projekts (2004) durchgeführt wurden. 
	Das gewonnene Wissen bietet sich für die Bearbeitung von Case Studies im internationalen und interkulturellen Kontext an.
  </Description>
  <Source type="website">
    <URI embedded="false" src="http://globe.bus.sfu.ca/results/countries/DEU?menu=country"/>
    <Author>Global Leadership and Organizational Behavior Effectiveness</Author>
    <Copyright>GLOBE</Copyright>
    <Stand>2016</Stand>
    <!-- Optional ab hier -->
    <Thumbnail src="http://globe.bus.sfu.ca/assets/culture-leadership-and-organization-bookcover-8e7598c4ae8aed4159bd4b43e9f14a43c9964e1f6f072ac873e5a7a7d9bbc6c4.jpg"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>Intercultural Management</Class>
    <!-- Optional ab hier -->
    <Professor>Prof. Dr. Nick-Magin</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>
