=== CLHB8/digital-learning-imbit/brillianideas/ux/xsd/Learning.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="learningType" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="youtube" />
      <xs:enumeration value="video" />
      <xs:enumeration value="website" />
      <xs:enumeration value="podcast" />
      <xs:enumeration value="seriousGame" />
      <xs:enumeration value="application" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Learning">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Title"/>
        <xs:element type="xs:string" name="Description"/>
        <xs:element name="Source">
          <xs:complexType>
            <xs:sequence>
			  <xs:choose>
				  <xs:element name="URI">
					<xs:complexType>
					  <xs:attribute type="xs:boolean" name="embedded" />
					  <xs:attribute type="xs:anyURI" name="src" />
					</xs:complexType>  
				  </xs:element>
				  <xs:element name="Video">
				    <xs:complexType>
					  <xs:attribute type="xs:boolean" name="embedded" />
					  <xs:attribute type="xs:string" name="id" />
					</xs:complexType>
				  </xs:element>
				  <xs:element name="App">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Android">
								<xs:complexType>
									<xs:attribute type="xs:string" name="id" />
								</xs:complexType>
							</xs:element>
							<xs:element name="iOS">
								<xs:complexType>
									<xs:attribute type="xs:string" name="id" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				  </xs:element>
			  </xs:choose>
              <xs:element type="xs:string" name="Author"/>
              <xs:element type="xs:string" name="Copyright"/>
              <xs:element type="xs:date" name="Stand" />
              <xs:element type="xs:duration" name="Duration" minOccurs="0" maxOccurs="1" />
              <xs:element name="Thumbnail">
                <xs:complexType>
                   <xs:attribute type="xs:anyURI" name="src"/>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:boolean" name="certificateCosts" minOccurs="0" maxOccurs="1" nillable="true" />
            </xs:sequence>
            <xs:attribute type="learningType" name="type"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="MetaInformation">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Class"/>
              <xs:element type="xs:string" name="Professor" minOccurs="0" maxOccurs="1"/>
              <xs:element type="guid" name="Recommended" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="guid" name="guid"/>
      <xs:attribute type="xs:boolean" name="cost"/>
      <xs:attribute type="xs:boolean" name="offerLimited"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CLHB8/digital-learning-imbit/ux/examples/Introduction_to_logic_MOOC_website.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="194f1c1b-d38a-4725-acbb-53e97ec1b2b9" cost="false" offerLimited="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Introduction to Logic</Title>
  <Description>
	Dieser Kurs bietet einen Einstieg in die Logik im Umfeld der rechnergestützen Informationsverarbeitung
	und stellt deren Anwendungsfelder vor.
	Zu den Kompetenzen die vermittelt werden, zählt das Formulieren von logische Sätze bzw. logische Formeln
	und es wird darauf eingegegangen, wie aus dieser Darstellung von Informationen eine logische Beweisführung möglich wird.
  </Description>
  <Source type="website">
    <URI embedded="false" src="https://www.coursera.org/learn/logic-introduction"/>
    <Author>Stanford University</Author>
    <Copyright>Coursera Inc.</Copyright>
    <Stand>2017</Stand>
    <!-- Optional ab hier -->
    <Thumbnail src="https://cdn.pixabay.com/photo/2016/11/13/13/29/puzzle-1821011_1280.jpg"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>Logik und Algebra</Class>
    <!-- Optional ab hier -->
    <Professor>Prof. Dr. Schwinn</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/Introduction_to_Economics_Macroeconomics_website.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="ed37a874-b6a8-47aa-a81c-a2c57e7269e0" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Introduction to Economics: Macroeconomics</Title>
  <Description>
  In diesem Wirtschaftskurs lernen Sie die Hauptkonzepte der Makroekonomie, wie Bruttoinlandsprodukt, Preislevel, Inflation, Arbeitslosigkeit, wirtschaftliches Wachstum und Zahlungsbilanz. Sie werden erkennen, dass sich die Makroekonomie nicht allzu sehr von der Mikroekonomie unterscheidet, da die Interaktion von Angebot und Nachfrage das grundsätzliche Organisationsframework zum Analysieren von Tätigkeiten einer nationales Wirtschaft darstellt. Sie werden lernen, wie die Equilibrium Ebenen des nationalen Einkommens und die Preise am Schnittpunkt der Kurven des gesamtwirtschaftlichen Angebots und der gesamtwirtschaftlichen Nachfrage bestimmt werden, genauso wie die Equilibrium Menge einer Transaktion und der Preis einer einzelnen Ware am Schnittpunkt der Angebots- und Nachfragekurven bestimmt werden.
  Dies ist ein Einführungskurs auf der elementarsten Ebene, so dass keine Vorkenntnisse der Ökonomie erforderlich ist.
  </Description>
  <Source type="website">
    <URI embedded="false" src="https://www.edx.org/course/introduction-economics-macroeconomics-snux-snu044-088-2x"/>
    <Author>Seoul National University</Author>
    <Copyright>2012-2017 edX Inc.</Copyright>
    <Stand>2017</Stand>
    <!-- Optional ab hier -->
    <Thumbnail src="https://www.edx.org/sites/default/files/styles/course_video_banner/public/course/image/featured-card/macroeconomics_318x210.jpg?itok=nzshdSy-"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>VWL</Class>
    <!-- Optional ab hier -->
    <Professor>Prof. Dr. Thomas Schuster</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/memrise_app.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="c46782ca-3c02-4360-a166-1156cb3df3e6" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Memrise</Title>
  <Description>
	Online Lerntool mit Karteikarten, hauptsächlich Sprachkurse, aber auch Kurse für andere akademische und nicht-akademische Fächer wie Wissenschaft, Musik, Geschichte, Philosophie oder Kultur
	</Description>
  <Source type="application">
    <App>
		<Android id="com.memrise.android.memrisecompanion" />
		<iOS id="635966718" />
	</App>
    <Author>Memrise Ltd</Author>
    <Copyright>Memrise Ltd</Copyright>
    <Stand>2017</Stand>
    <!-- Optional ab hier -->
    <Thumbnail src="https://fthmb.tqn.com/mmyEgRJ2P7RVlkt9OZOXzZ5USWE=/2400x1400/filters:no_upscale()/about/memrise-logo-579bd4db5f9b589aa9789d2a.png"/>
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>Spanisch</Class>
    <!-- Optional ab hier -->
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>

=== CLHB8/digital-learning-imbit/ux/examples/youtube_embedded_umgedrehte_mathe.xml
<?xml version="1.0" encoding="utf-8"  ?>
<?xml-stylesheet type="text/xsl" href="../xslt/Learning.xsl"?>
<Learning guid="0bfcfe0c-e5e4-449f-9483-6d2f29ef0e31" cost="false" offerLimited="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com ../xsd/Learning.xsd">
  <Title>Input out: Die umgedrehte Mathematikvorlesung</Title>
  <Description>
	Die Vortragsaufzeichnung mit Folien gibt es im elearning-center der TU-Darmstadt, dessen Team auch das Video erstellt hat: http://www.e-learning.tu-darmstadt.de...
  </Description>
  <Source type="youtube">
    <Video embedded="true" id="tGiRCUnoNXk"/>
    <Author>Christian Spannagel</Author>
    <Copyright>Christian Spannagel</Copyright>
    <Stand>2012-02-12</Stand>
    <!-- Optional ab hier -->
    <!--  Optional Ende -->
  </Source>
  <MetaInformation>
    <Class>Mathematikvorlesung</Class>
    <!-- Optional ab hier -->
    <Professor>Lang</Professor>
    <!--  Optional Ende -->
  </MetaInformation>
</Learning>
